name: Build and Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Temurin을 사용하여 JDK 설치
        architecture: x64

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: |
        docker build -t kimseonik/studyfy-app:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag kimseonik/studyfy-app:${{ github.sha }} kimseonik/studyfy-app:latest
        docker push kimseonik/studyfy-app:${{ github.sha }}
        docker push kimseonik/studyfy-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
        chmod 600 ~/.ssh/ec2_key
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/ec2_key
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2_key ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker pull kimseonik/studyfy-app:latest
          docker stop studyfy-app || true
          docker rm studyfy-app || true
          docker run -d -p 8080:8080 --name studyfy-app kimseonik/studyfy-app:latest
        EOF
