name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Build Docker image
      run: docker build -t kimseonik/studyfy-app:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag kimseonik/studyfy-app:${{ github.sha }} kimseonik/studyfy-app:latest
        docker push kimseonik/studyfy-app:${{ github.sha }}
        docker push kimseonik/studyfy-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Create .env from secret
      run: echo "${{ secrets.ENV_PRODUCTION }}" > .env

    - name: Add EC2 to known_hosts
      run: ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        scp docker-compose.yml .env \
          ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/apps/server/

    - name: Deploy on EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e
          cd /home/ubuntu/apps/server
          docker pull kimseonik/studyfy-app:latest
          docker compose --env-file .env down || true
          docker compose --env-file .env up -d
        EOF
